package ui.buttons;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import game.BattleCounter;
import game.Game;
import ui.PanelManager;

/**
 * Represents a button in the UI that resets the battle counter and changes the screen to player selection.
 */
public class ChangeClassButton extends JButton implements ActionListener {

    /**
     * Constructs a button with the text "Change Class" and adds an action listener to handle button clicks.
     */
    public ChangeClassButton(){
        this.addActionListener(this);
        this.setText("Change Class");
    }

    /**
     * Resets the battle counter and changes the screen to player selection when the button is clicked.
     *
     * @param e The action event generated by the button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        Game.getInstance().getBattleCounter().reset();
        PanelManager.changeToPlayerSelection();
    }
}
