package ui.buttons;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import game.Game;
import game.characters.Player;

/**
 * Represents a button in the UI that starts the next battle and restores the player's health.
 */
public class NextBattleButton extends JButton implements ActionListener {

    /**
     * Constructs a button with the text "Next Battle" and adds an action listener to handle button clicks.
     */
    public NextBattleButton() {
        this.setText("Next Battle");
        this.addActionListener(this);
    }

    /**
     * Restores the player's health and creates a new battle when the button is clicked.
     *
     * @param e The action event generated by the button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        Player player = Game.getInstance().getPlayer();

        player.restoreHealth();
        Game.getInstance().createBattle();
    }
}
