package ui.buttons;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import game.Game;
import ui.PanelManager;
import game.characters.Player;

/**
 * Represents a button in the UI that allows the user to select a player class.
 * When clicked, it creates a new player of the selected class and starts a new battle.
 */
public class SelectClassButton extends JButton implements ActionListener {

    private final String playerIdentifier;

    /**
     * Constructs a button for selecting a player class.
     *
     * @param newPlayerIdentifier The identifier of the player class to be selected.
     */
    public SelectClassButton(String newPlayerIdentifier) {

        playerIdentifier = newPlayerIdentifier;

        this.setText("Select " + playerIdentifier);
        this.addActionListener(this);
    }

    /**
     * When the button is clicked, it sets the new player class and initiates a new battle.
     * It then switches the panel to the battle view.
     *
     * @param e The action event generated by the button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {

        Player newPlayer = new Player(playerIdentifier);
        Game.getInstance().setPlayer(newPlayer);

        Game.getInstance().createBattle();

        PanelManager.changeToBattle();
    }
}
