package ui.buttons;

import ui.PanelManager;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Represents a button in the UI that allows the user to view the credits.
 * When clicked, it switches the panel to the credits screen.
 */
public class ShowCreditsButton extends JButton implements ActionListener {

    /**
     * Constructs the "Show Credits" button.
     * It sets the button's label and adds an action listener for button clicks.
     */
    public ShowCreditsButton(){
        this.setText("Show Credits");
        this.addActionListener(this);
    }

    /**
     * When the button is clicked, this method is called to switch the UI to the credits screen.
     *
     * @param e The action event generated by the button click.
     */
    @Override
    public void actionPerformed(ActionEvent e) {

        PanelManager.changeToCredits();
    }
}
